# from langchain_openai import ChatOpenAI
# # from langchain.prompts import PromptTemplate
# from langchain_core.prompts import ChatPromptTemplate
# import os
# from dotenv import load_dotenv
#
# load_dotenv()
#
# llm = ChatOpenAI(
#     model="gpt-4o-mini",
#     api_key=os.getenv("OPENAI_API_KEY"),
#     temperature=0
#
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
import os
from dotenv import load_dotenv

load_dotenv()

# 3. CHANGE THE LLM HERE:
llm = ChatGroq(
    model="llama-3.1-8b-instant", # Free Llama-3.1 model (updated from deprecated llama3-8b-8192)
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0
)

# prompt = PromptTemplate(
#     input_variables = ["context", "question"],
#     template = """
#         You are a clothing and textiles information assistant. You have to retrieve the data from the given database and answer the question in human readable natural language.
#         
#         Answer ONLY using the context below.
# 
#         Context:
#         {context}
# 
#         Question:
#         {question}
# 
#         Answer clearly in simple English.
#     """
# )

prompt = ChatPromptTemplate.from_template(
    """
    You are a professional Bridal Shop Information Assistant. 
    Use the provided Context to answer the user's question accurately.

    FORMATTING RULES:
    1. Always use a **Numbered List** for multiple items.
    2. **Bold** the names of the clothing/jewelry items.
    3. *Italicize* the attire codes (e.g., *LE004*).
    5. Do NOT show database ID columns; use Names and Codes only.
    6. Use emojis in friendly manner.

    STRICT CONSTRAINTS:
    - Only answer based on the provided Context. 
    - If the answer is not in the Context, professionally state that "Sorry,I do not have that information. I am just a Bridal Shop assistant.".
    - Do not provide any thing rather than your database or regarding the shop.
    
    Context:
    {context}

    Question:
    {question}

    Answer:
    """
)

def rag_answer(vectorstore, question):
    docs = vectorstore.similarity_search(question, k=30)
    #changing K valu is hyperparameter tuning, it is the number of similar documents to retrieve from the vectorstore.
    # You can experiment with different values of K to see how it affects the quality of the answers generated by the LLM. A higher K value may provide more context for the LLM,
    # but it may also introduce more noise if the retrieved documents are not relevant enough. A lower K value may provide more focused context, but it may also miss out on important information. You can start with a moderate K value
    # (e.g., 10 or 20) and adjust it based on the performance of the LLM and the relevance of the retrieved documents.
    context = "\n".join(doc.page_content for doc in docs)
    
    response = llm.invoke(
        prompt.format(context=context, question=question)
    )
    
    return response.content